# This is the configuration used to check the rubocop source code.
# Check out: https://github.com/bbatsov/rubocop

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.5.1
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'node_modules/**/*'
    - 'db/**/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'client/node_modules/**/*'
    - 'bin/**/*'
    - !ruby/regexp /old_and_unused\.rb$/

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

#Style/MultilineBlockChain:
#  Enabled: false
  
#Layout/SpaceInsideBlockBraces:
#  Enabled: false
#  
#Lint/Void:
#  Enabled: false